export class ProgramPercentage {

    constructor(
        public education: number,
        public mathematics: number,
        public business_Marketing: number,
        public communications_Technology: number,
        public language: number,
        public visual_Performing: number,
        public engineering_Technology: number,
        public parks_Recreation_Fitness: number,
        public agriculture: number,
        public security_Law_Enforcement: number,
        public computer: number,
        public precision_Production: number,
        public humanities: number,
        public library: number,
        public psychology: number,
        public social_Science: number,
        public legal: number,
        public english: number,
        public construction: number,
        public military: number,
        public communication: number,
        public public_Administration_Social_Service: number,
        public architecture: number,
        public ethnic_Cultural_Gender: number,
        public resources: number,
        public health: number,
        public engineering: number,
        public history: number,
        public theology_Religious_Vocation: number,
        public transportation: number,
        public physical_Science: number,
        public science_Technology: number,
        public biological: number,
        public family_Consumer_Science: number,
        public philosophy_Religious: number,
        public personal_Culinary: number,
        public multidiscipline: number,
        public mechanic_Repair_Technology: number

    ) {
        this.education = education;
        this.mathematics = mathematics;
        this.business_Marketing = business_Marketing;
        this.communications_Technology = communications_Technology,
        this.language = language,
        this.visual_Performing = visual_Performing,
        this.engineering_Technology = engineering_Technology,
        this.parks_Recreation_Fitness = parks_Recreation_Fitness,
        this.agriculture = agriculture,
        this.security_Law_Enforcement = security_Law_Enforcement,
        this.computer = computer,
        this.precision_Production = precision_Production,
        this.humanities = humanities,
        this.library = library,
        this.psychology = psychology,
        this.social_Science = social_Science,
        this.legal = legal,
        this.english = english,
        this.construction = construction,
        this.military = military,
        this.communication = communication,
        this.public_Administration_Social_Service = public_Administration_Social_Service,
        this.architecture = architecture,
        this.ethnic_Cultural_Gender = ethnic_Cultural_Gender,
        this.resources = resources,
        this.health = health,
        this.engineering = engineering,
        this.history = history,
        this.theology_Religious_Vocation = theology_Religious_Vocation,
        this.transportation = transportation,
        this.physical_Science = physical_Science,
        this.science_Technology = science_Technology,
        this.biological = biological,
        this.family_Consumer_Science = family_Consumer_Science,
        this.philosophy_Religious = philosophy_Religious,
        this.personal_Culinary = personal_Culinary,
        this.multidiscipline = multidiscipline,
        this.mechanic_Repair_Technology = mechanic_Repair_Technology
    }
    
}